services:

  postgres:
    container_name: postgres
    image: postgres:16.3
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "5432"
      POSTGRES_DB: "estate_service"
    volumes:
      - ./app_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  service:
    container_name: service
    build:
      context: .
    restart: always
    env_file:
      - .env
    environment:
      APP_ENV: prod
      HOST: 0.0.0.0
      PORT: 8080
      PG_USER: postgres
      PG_PASSWORD: 5432
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DATABASE: estate_service
    volumes:
      - ./config.yaml:/app/config.yaml
    ports:
      - "8080:8080"
    depends_on:
      - postgres